test post section

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,18 +1,28 @@
 pipeline {
-	agent {
-		docker { image 'python:3.5.1' }
-	}
+	agent any
 	stages {
-		stage('Build') {
+		stage('Test') {
 			steps {
-				sh 'pwd'
-				sh 'echo "**********"'
-				sh 'echo $PATH'
-				sh 'echo "**********"'
-				sh 'python --version'
-				sh 'echo "**********"'
-				sh 'echo $USER'
+				sh 'echo "failed"; exit 127'
 			}
+		}
+	}
+	post {
+		always {
+			echo "This will always run"
+		}
+		success {
+			echo "This will run only if successful"
+		}
+		failure {
+			echo "This will run only if failed"
+		}
+		unstable {
+			echo "This will run only if the run was marked as unstable"
+		}
+		changed {
+			echo "This will run only if the state of the Pipeline has changed"
+			echo 'For example, if the Pipeline was previously failing but is now successful'
 		}
 	}
 }
